eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    # 这个构造的访问路径是：http://localhost:8769/eureka-client/v1/eureka-client/test/post/name，即HOST:PORT/serviceId/path 才会被转发到serviceId对应的服务
    eureka-client:
      path: /v1/eureka-client/**
      serviceId: eureka-client